[phases.setup]
nixPkgs = ["php", "nginx", "libmysqlclient"]
nixLibs = ["libmysqlclient"]
aptPkgs = []

[phases.install]
dependsOn = ["setup"]
cmds = ["mkdir -p /var/log/nginx && mkdir -p /var/cache/nginx"]

[phases.start]
cmd = "node /assets/scripts/prestart.mjs /assets/nginx.template.conf /nginx.conf && (php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf)"
